name = "tmdb-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
	{ pattern = "api.xn--b1a5a.fun/*", zone_name = "xn--b1a5a.fun" },
	{ pattern = "xn--b1a5a.fun/*", zone_name = "xn--b1a5a.fun" }
]

[triggers]
crons = []

[[r2_buckets]]
binding = "TMDB_CACHE_BUCKET"
bucket_name = "tmdb-cache"
preview_bucket_name = "tmdb-cache-preview"

[[r2_buckets]]
binding = "VIBE_STATIC_BUCKET"
bucket_name = "vibe-static"
preview_bucket_name = "vibe-static-preview"
